import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const [name, setName] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <input
          type="text"
          placeholder="username"
          onChange={(e) => setName(e.target.value)}
        />
        <button onClick={() => router.push(`/todo/${name}/`)}>Нэвтрэх</button>
      </div>
    </div>
  );
}
